# Generated by Django 5.1.7 on 2025-03-29 09:20

import Events.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('Capacity', models.IntegerField()),
                ('Description', models.CharField(max_length=200)),
                ('date', models.DateField(default=Events.models.get_today_date)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateField(default=Events.models.get_today_date)),
                ('location', models.CharField(max_length=255)),
                ('registration_status', models.CharField(choices=[('full', 'full'), ('open', 'open'), ('pending', 'pending')], default='pending', max_length=10)),
                ('event_type', models.CharField(choices=[('online', 'online'), ('in-person', 'In-person')], default='in-person', max_length=10)),
                ('Category', models.CharField(max_length=25)),
                ('event_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('cancelled', 'Canselled')], default='upcoming', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Events.eventsmodel')),
            ],
        ),
    ]
