# Generated by Django 5.1.7 on 2025-03-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_eventregistration_user_eventsmodel_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='ticket_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
