# Generated by Django 5.1.7 on 2025-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='event_status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('cancelled', 'Canselled'), ('finished', 'Finished')], default='upcoming', max_length=10),
        ),
    ]
